sudar/email-log

HISTORY.md, email-log.php, include/class-email-header-parser.php, include/class-email-log-list-table.php
Inline documentation added to improve code readability and maintainability.
=> Adding inline documentation

HISTORY.md, email-log.php, include/class-email-log-list-table.php
**Fix #38**
The access modifiers has been explicitly specified as a good practice.
=> Add access modifiers to class methods

include/EmailLogAutoloader.php
@sudar requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/sudar/email-log/
=> Scrutinizer Auto-Fixes

include/Core/UI/Page/LogListPage.php
This allows add-ons to hook on to `el_admin_footer` action.
=> Enable the `el_admin_footer` custom hook for addons use

include/Core/DB/TableManager.php
**Question**:
1. Would it be better to include column names instead of `*` in the SQL query?
=> Move `Fetch log item by ID` to TableManger in Core

include/Addon/addon-helper.php
This is part of the discussion [here](https://github.com/sudar/email-log-forward-email/pull/1#discussion_r98343793)
=> Inversion of control by passing dependencies in Constructor

include/Core/DB/TableManager.php
This method is required for implementing #25
=> Add a method to delete logs beyond given interval in TableManager class

include/Core/DB/TableManager.php, include/Core/UI/ListTable/LogListTable.php, include/Util/helper.php
This code is part of the Export Logs addon.
=> Modify TableManager class to get logs to export as CSV

assets/css/admin/view-logs.css, assets/js/admin/view-logs.js, bower.json, include/Core/Request/LogListAction.php, include/Core/UI/ListTable/LogListTable.php, include/Core/UI/Page/LogListPage.php
**What's new in this PR?**
- Prevented Thickbox from opening as iFrame
- The JS and CSS needed for AJAX content has been added to View Logs page
- Standardised naming conventions
=> Add HTML/Text tabs to Thickbox

include/Core/UI/Page/BasePage.php
=> Update Plugin's screen help links

include/Core/EmailLog.php, include/Core/Request/LogListAction.php, include/Core/UI/Setting/EmailLogSetting.php, include/Util/helper.php, load-email-log.php
=> Introduce GUI option to change capability

email-log.php, include/Addon/Addon.php, include/Addon/AddonList.php, include/Addon/License/Licenser.php, include/Core/UI/Page/BasePage.php
=> 140 fix/open links in new tab

include/Core/DB/TableManager.php, uninstall.php
=> 66 fix/replace wp get sites() with get sites()

assets/js/admin/view-logs.js
Fixes https://github.com/sudar/email-log/issues/138
=> Set HTML view as the default email log preview

include/Core/DB/TableManager.php, include/Core/EmailLogger.php
Closes https://github.com/sudar/email-log/issues/106
Closes https://github.com/sudar/email-log/issues/112
Closes https://github.com/sudar/email-log/issues/31
=> 106 feature/store attachment name

include/Core/Request/LogListAction.php, include/Core/UI/Component/DashboardWidget.php, include/Util/helper.php
Closes https://github.com/sudar/email-log-auto-delete-logs/issues/5, Fixes https://github.com/sudar/email-log-auto-delete-logs/issues/4
=> Display Auto delete logs next cron schedule in local time

include/Core/DB/TableManager.php
Close https://github.com/sudar/email-log/issues/169
=> Increase `to` and `subject` column length

include/Core/DB/TableManager.php
Fix https://github.com/sudar/email-log/issues/170
=> Ensure trim() is used only on strings.

include/Core/DB/TableManager.php, include/Util/helper.php
Fix https://github.com/sudar/email-log/issues/171
=> Ensure trim() is always used on string value and not on array type

include/Core/UI/Setting/CoreSetting.php, include/Util/helper.php
Fix https://github.com/sudar/email-log/issues/184
=> Implement Notification email reset UI

include/Core/UI/ListTable/LogListTable.php
This PR is part of https://github.com/sudar/email-log-advanced-search/issues/8
=> Include filter on `To` field in the Log list page

include/Core/EmailLogger.php
This also adds compatibility with WP SES plugin
Fix #194
Fix #198
=> Do not modify value passed to the filter

include/Util/helper.php
This PR is part of https://github.com/sudar/email-log-advanced-search/issues/7
=> Add a helper method to EmailLog\Util namespace

assets/css/admin/addon-list.css, assets/css/admin/view-logs.css, include/Addon/Addon.php, include/Addon/License/Licenser.php, include/Core/UI/ListTable/LogListTable.php, include/Util/helper.php, include/compatibility/wpmandrill.php
=> PR: Css changes to support WP5.3

HISTORY.md, include/Core/EmailLogger.php
=> PR: Add basic actions to log buddy press emails.

include/Core/UI/ListTable/LogListTable.php
=> PR: Add seconds to sent time.

Gruntfile.js, include/Core/UI/Page/LogListPage.php, package-lock.json, package.json
=> Replace bower with npm

uninstall.php
Fix: https://github.com/sudar/email-log-mask-fields/issues/14
=> PR: Remove data stored by mask fields addon

tests/wp-tests/uninstall/UninstallWithDeleteTest.php, tests/wp-tests/uninstall/UninstallWithoutDeleteTest.php
=> PR: Fix DB version in tests.

include/Core/UI/Component/DashboardWidget.php, include/Util/helper.php
Fix #254
Requires https://github.com/sudar/email-log-auto-delete-logs/pull/12
=> PR: Use hook instead of helper function.

include/Core/DB/TableManager.php, include/Core/UI/ListTable/LogListTable.php
=> PR: Add sent status filter

assets/js/admin/view-logs.js, include/Core/UI/ListTable/LogListTable.php, include/Core/UI/Page/LogListPage.php, include/Util/helper.php
Fix #302 
Required by https://github.com/sudar/email-log-summary/pull/12
=> PR: Ability to view log in browser

include/Core/DB/TableManager.php, include/Core/EmailLogger.php, include/Core/UI/Page/SettingsPage.php
Fix #305
Required by PR:https://github.com/sudar/email-log-import-logs/pull/3
=> PR: Return status from log email function and make form ready to handle uploads

composer.json, composer.lock
=> Include WordPress coding standard as a dependency
